// Freeze this file once approved. New design work gets a new version directory.
export function render(s, e) {
  const b = s.business, name = e(b.name.value), location = e(b.location.value);
  const logo = s.assets.logo ? `<img class="logo" src="${e(s.assets.logo.path)}" alt="${e(s.assets.logo.alt)}">` : `<strong>${name}</strong>`;
  const hero = s.assets.images[0] ? `<img class="hero-image" src="${e(s.assets.images[0].path)}" alt="${e(s.assets.images[0].alt)}">` : '<div class="art" aria-hidden="true"><span>+</span></div>';
  const phone = b.phone?.value.replace(/[^+\d]/g,'');
  const contact = phone ? `<a class="button" href="tel:${e(phone)}">Call ${e(b.phone.value)} ↗</a>` : '<p>Contact details awaiting confirmation.</p>';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>${name} — concept by Parley</title><style>
  *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f3eb;color:#203c37;font:17px/1.6 system-ui,sans-serif}a{color:inherit}h1,h2,h3,p{margin:0}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.06;letter-spacing:-.04em}h1{font-size:clamp(44px,6.5vw,88px)}h2{font-size:clamp(34px,4vw,56px)}.wrap{width:80%;max-width:1240px;margin:auto}.banner{padding:12px 5%;background:#203c37;color:white;text-align:center;font-size:12px;letter-spacing:.05em}nav{display:flex;justify-content:space-between;align-items:center;gap:24px;padding:28px 0;border-bottom:1px solid #ccd4ca}nav a{text-decoration:none}nav div{display:flex;gap:24px}.logo{max-width:180px;max-height:64px;object-fit:contain}.hero{display:grid;grid-template-columns:1.15fr 1fr;gap:7%;align-items:center;padding:90px 0}.eyebrow{text-transform:uppercase;font-size:12px;letter-spacing:.15em;margin-bottom:24px}.intro{max-width:520px;margin:28px 0}.button{display:inline-block;padding:14px 24px;background:${s.brand.accent};color:white;border-radius:4px;text-decoration:none}.art,.hero-image{width:100%;height:480px;object-fit:cover;border-radius:180px 180px 12px 12px}.art{display:grid;place-items:center;background:#d9e3d5}.art span{font:180px Georgia;color:${s.brand.accent}}section.detail{padding:64px 0;border-top:1px solid #ccd4ca}.services{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:36px}.card{background:#e9ede2;padding:28px;border-radius:8px}.card small{display:block;margin-bottom:20px}.contact{display:grid;grid-template-columns:1fr 1fr;gap:40px}.contact p{margin:20px 0}.example{border:1px dashed #83958a;padding:22px;margin-top:20px}.example small{display:block;font-weight:700;margin-bottom:12px}footer{padding:32px 0;font-size:12px;border-top:1px solid #ccd4ca}@media(max-width:700px){.wrap{width:90%}nav{align-items:flex-start}nav div{gap:12px;font-size:13px}.hero{grid-template-columns:1fr;padding:50px 0;gap:36px}.art,.hero-image{height:320px}.services,.contact{grid-template-columns:1fr}.banner{font-size:11px}}
  </style></head><body><div class="banner">${s.demo ? 'FICTIONAL DEMO' : 'CONCEPT WEBSITE'} · Prepared by Parley Systems · Not the business’s official website</div><div class="wrap"><nav aria-label="Main navigation">${logo}<div><a href="#services">Services</a><a href="#contact">Contact</a></div></nav><main><section class="hero"><div><p class="eyebrow">${location} / ${e(s.sector)}</p><h1>${e(s.copy.headline)}</h1><p class="intro">${e(s.copy.introduction)}</p><a class="button" href="#services">Explore services ↗</a></div>${hero}</section><section id="services" class="detail"><p class="eyebrow">Explore your options</p><h2>Care starts here.</h2><div class="services">${b.services.map((x,i)=>`<article class="card"><small>0${i+1}</small><h3>${e(x.value)}</h3></article>`).join('') || '<p>Service details awaiting confirmation.</p>'}</div></section>${s.exampleSections.map(x=>`<aside class="example"><small>ILLUSTRATIVE CONTENT — NOT A VERIFIED BUSINESS CLAIM</small><h3>${e(x.title)}</h3><p>${e(x.body)}</p></aside>`).join('')}<section class="detail contact" id="contact"><div><p class="eyebrow">Get in touch</p><h2>Start a conversation.</h2><p>${name}, ${location}</p>${contact}</div><div>${b.address?`<p>${e(b.address.value)}</p>`:''}${b.hours?`<p>${e(b.hours.value)}</p>`:''}${b.website?`<p><a href="${e(b.website.value)}" rel="noreferrer">Visit the official website ↗</a></p>`:''}</div></section></main><footer>${name} · ${s.demo?'Fictional demonstration':'Unapproved design concept'} by Parley Systems. Photography may be illustrative. No bookings or payments are taken on this concept.</footer></div></body></html>`;
}
